# Generated by Django 3.2.7 on 2021-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default='content'),
            preserve_default=False,
        ),
    ]
